psqlDB:
  host: localhost
  port: 5432
  dbName: postgres
  user: postgres
  password: pass@123
  maxOpenConnections: 20
  maxIdleConnections: 10
  connMaxLifetimeInHour: 24
  connMaxIdleTimeInMinute: 0